"""Add all sensor features to SensorReading

Revision ID: dd080486e170
Revises: 046261744eef
Create Date: 2025-07-24 16:41:43.632910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd080486e170'
down_revision = '046261744eef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Temperature', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('Vibration', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('Pressure', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('Humidity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('SoundLevel', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('OperatingHours', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('LastMaintenanceDays', sa.Float(), nullable=True))
        batch_op.drop_column('pressure')
        batch_op.drop_column('temp')
        batch_op.drop_column('vibration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vibration', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('temp', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('pressure', sa.FLOAT(), nullable=True))
        batch_op.drop_column('LastMaintenanceDays')
        batch_op.drop_column('OperatingHours')
        batch_op.drop_column('SoundLevel')
        batch_op.drop_column('Humidity')
        batch_op.drop_column('Pressure')
        batch_op.drop_column('Vibration')
        batch_op.drop_column('Temperature')

    # ### end Alembic commands ###
